/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/worker-configuration.d.ts` (hash: 768e7bc39935609a820d91879bca5c11)
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: "development";
	PUBLIC_ORIGIN: "http://localhost:4321";
	ROUND_SESSIONS: DurableObjectNamespace<import("./src/index").RoundSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RoundSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "PUBLIC_ORIGIN">> {}
}
