/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/worker-configuration.d.ts` (hash: cc74c30853f9bb6764e85c32f0b3c098)
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: "production" | "development";
	PUBLIC_ORIGIN: "https://golf.stateofstick.co" | "http://localhost:4321";
	ROUND_SESSIONS: DurableObjectNamespace<import("./src/index").RoundSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RoundSession";
	}
	interface ProductionEnv {
		DB: D1Database;
		ENVIRONMENT: "production";
		PUBLIC_ORIGIN: "https://golf.stateofstick.co";
		ROUND_SESSIONS: DurableObjectNamespace<import("./src/index").RoundSession>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "PUBLIC_ORIGIN">> {}
}
